import type { DummyRuleMap } from 'oxlint';

export default {
  'react-js/hook-use-state': 'warn',
  'react-js/jsx-sort-props': ['warn', { reservedFirst: true }],
  'react-js/no-unstable-nested-components': ['error', { allowAsProps: true }],
  'react/error-boundaries': 'error',
  'react/exhaustive-effect-dependencies': 'error',
  'react/function-component-definition': 'warn',
  'react/globals': 'error',
  'react/hooks': 'error',
  'react/immutability': 'error',
  'react/incompatible-library': 'error',
  'react/invariant': 'error',
  'react/jsx-boolean-value': 'warn',
  'react/jsx-curly-brace-presence': 'warn',
  'react/jsx-fragments': 'warn',
  'react/jsx-no-constructed-context-values': 'error',
  'react/jsx-no-useless-fragment': ['warn', { allowExpressions: true }],
  'react/jsx-pascal-case': 'warn',
  'react/memo-dependencies': 'error',
  'react/no-deriving-state-in-effects': 'error',
  'react/no-object-type-as-default-prop': 'error',
  'react/preserve-manual-memoization': 'error',
  'react/purity': 'error',
  'react/refs': 'error',
  'react/self-closing-comp': 'warn',
  'react/set-state-in-effect': 'error',
  'react/set-state-in-render': 'error',
  'react/static-components': 'error',
  'react/unsupported-syntax': 'error',
  'react/use-memo': 'error',
  'react/void-use-memo': 'error',
} satisfies DummyRuleMap;
