import type { DummyRuleMap } from 'oxlint';

// TODO: add `object-shorthand` once it's released https://github.com/oxc-project/oxc/commit/0f01fbdf7fd6e65fb7c4402d8214114d283ff7ea
export default {
  curly: 'warn',
  'default-case-last': 'error',
  'default-param-last': 'error',
  eqeqeq: 'error',
  'func-names': ['error', 'as-needed'],
  'grouped-accessor-pairs': 'error',
  'guard-for-in': 'error',
  'no-array-constructor': 'error',
  'no-await-in-loop': 'error',
  'no-bitwise': 'error',
  'no-case-declarations': 'error',
  'no-console': ['error', { allow: ['warn', 'error', 'info'] }],
  'no-constant-binary-expression': 'error',
  'no-constructor-return': 'error',
  'no-else-return': 'warn',
  'no-empty': 'error',
  'no-empty-function': 'error',
  'no-eval': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-extra-label': 'error',
  'no-fallthrough': 'error',
  'no-implicit-coercion': ['warn', { allow: ['!!'] }],
  'no-implied-eval': 'error',
  'no-iterator': 'error',
  'no-label-var': 'error',
  'no-labels': 'error',
  'no-lone-blocks': 'error',
  'no-lonely-if': 'warn',
  'no-multi-assign': 'error',
  'no-new': 'error',
  'no-new-func': 'error',
  'no-new-wrappers': 'error',
  'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
  'no-promise-executor-return': 'error',
  'no-proto': 'error',
  'no-prototype-builtins': 'error',
  'no-redeclare': 'error',
  'no-return-assign': 'error',
  'no-script-url': 'error',
  'no-self-compare': 'error',
  'no-sequences': 'error',
  'no-template-curly-in-string': 'error',
  'no-unmodified-loop-condition': 'error',
  'no-unneeded-ternary': 'error',
  'no-unused-vars': [
    'error',
    {
      args: 'after-used',
      argsIgnorePattern: '^_',
      ignoreRestSiblings: false,
      vars: 'all',
      varsIgnorePattern: '^_',
    },
  ],
  'no-useless-call': 'error',
  'no-useless-computed-key': 'warn',
  'no-useless-concat': 'error',
  'no-useless-constructor': 'error',
  'no-useless-rename': 'warn',
  'no-useless-return': 'warn',
  'no-var': 'error',
  'operator-assignment': 'warn',
  'prefer-const': 'warn',
  'prefer-exponentiation-operator': 'warn',
  'prefer-numeric-literals': 'error',
  'prefer-object-has-own': 'error',
  'prefer-object-spread': 'warn',
  'prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'warn',
  'symbol-description': 'error',
  yoda: 'warn',
} as DummyRuleMap;
