name: Setup Environment
description: Sets up environment by installing all necessary dependencies.

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v5

    - name: Use Node.js 24
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm i
