import { defineConfig } from 'oxfmt';

export default defineConfig({
  printWidth: 80,
  arrowParens: 'avoid',
  trailingComma: 'all',
  endOfLine: 'lf',
  semi: true,
  useTabs: false,
  tabWidth: 2,
  bracketSpacing: true,
  singleQuote: true,
  bracketSameLine: false,
  sortPackageJson: true,
  sortImports: {
    groups: [
      'type-builtin',
      'type-external',
      'type-internal',
      'type-subpath',
      'type-parent',
      'type-sibling',
      'type-index',
      { newlinesBetween: true },
      'side_effect',
      { newlinesBetween: true },
      'builtin',
      { newlinesBetween: true },
      'external',
      { newlinesBetween: true },
      'internal',
      'subpath',
      'parent',
      'sibling',
      'index',
      'style',
      { newlinesBetween: true },
      'unknown',
    ],
    newlinesBetween: false,
  },
});
