name: Release

on:
  push:
    branches: [main, canary]

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Environment
        uses: ./.github/actions/setup-environment

      - name: Release
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  sync-canary:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [release]
    name: Sync canary with main
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: canary
          token: ${{ secrets.CI_GITHUB_PAT }}

      - name: Back-merge main into canary
        run: |
          git merge --ff-only origin/main
          git push
